### PR TITLE
JCOR-297 Update Play version to 2.6.6

### PR DESCRIPTION
**Pull request by gabelorenzo**
https://jaroop.atlassian.net/browse/JCOR-297

### CODE REVIEW

**Comment by mhzajac** [comment]
The Scala version for 2.11.x in the root project can be bumped up.

**Comment by gabelorenzo** [comment]
What about this card https://jaroop.atlassian.net/browse/JCOR-296 ?

**Comment by mhzajac** [comment]
I mean the version here is 2.11.7, but the latest on that binary version is 2.11.11.

**Comment by gabelorenzo** [comment]
Updated

**Pull request merged**
